language: r
sudo: false
cache: 
  packages: yes
  directories: 
    - $TRAVIS_BUILD_DIR/_bookdown_files
env:
  global:
  - secure: CekAzEMeJ3C5Jhz24GCG6UAYJoOUvh/v7LDKw21ZamF3DJ5kNEM4nPPG87+Jg7VNMfvsSvmpO3Gjvn22NsAkS3Ub9PX4m5CkRuR9DjXWVel5AZP3b9Q2YCbJAbBiR/ksh6UEpziXP9fJkPdP8MIugMgZ/7slbOgMaAmfT0Vo46FKmHLstvJT24tHwcQw6GRmpu5QMMOS+OxnYywVGGHVAUVV5FNPEYV31N1O6jUe97c7/RARppBg2G5mjiC+c+Riuy96eWyJAw+G/z7P2dr524oXIR0gXhmJb4NgSYYw4KUx4IG7glbZ1aZmwpUUSWGkR1/3Rith/4GPRd8Ta57O37W5xkxZ7D+fQnsQSFkYRbm4TB8/dnGfl4fpphLmX8njOXCIhfXlTc3HHEdewOoDZTqSNa0O4+tQ05uiAxvjIxI6R48NPcJpICCOd/E0IuILXETBWcNWBkN63PpUrP2ShPyHk+jTHvgsN5nI3CTy0HdPC560evz/wo1LAZMCFm5viBJ1RcfaJQ/3oDgtHV0ZMHZIuVwNnAvFYcmVKf0THpVW8J2ZouoDxkWrc/oFFEg9C+QLIvhX8ooVD9LNlS8L5NS+VmEsS3pFe4NNJWkimO0ve+7UvFSrJNjcc7ImBM033ZuRxhRx9pltyc3mshu9ysX+1CnYmI3RP7EB8RDP4hc=
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- ./_build.sh
- ./_deploy.sh
